### ISSUE TITLE
test

### ISSUE THREAD

**Issue by Axkaban** [luckyguy73/capstone-final-expresso#2]
Once express et al. were installed, you've passed 68 out of 89 tests, here's the console output. Not concern with it though, What I mainly care about is how you wrote the passing methods since we are not talking about tables. But I thought you would care to see.
```
Server is listening on port 8081
  Employee Table
    1) should exist
    2) should have name, position, wage, and is_current_employee columns with appropriate data types
    3) should have a required name column
    4) should have a required position column
    5) should have a required wage column
    6) is_current_employee should default to 1

  Timesheet Table
    7) should exist
    8) should have id, name, and description columns with appropriate data types
    9) should have a required hours column
    10) should have a required rate column
    11) should have a required date column
    12) should have a required employee_id column

  Menu Table
    13) should exist
    14) should have id and title columns with appropriate data types
    15) should have a required title column

  MenuItem Table
    16) should exist
    17) should have id, name, description, inventory, price, and menu_id columns with appropriate data types
    18) should have a required name column
    19) should have a required inventory column
    20) should have a required price column
    21) should have a required menu_id column

  GET /api/employees
GET /api/employees 200 184 - 8.913 ms
    ✓ should return all currently-employed employees (72ms)
GET /api/employees 200 184 - 1.131 ms
    ✓ should return a status code of 200

  GET /api/employees/:id
GET /api/employees/2 200 97 - 1.788 ms
    ✓ should return the employee with the given ID
GET /api/employees/2 200 97 - 0.639 ms
    ✓ should return a 200 status code for valid IDs
GET /api/employees/999 404 - - 0.459 ms
    ✓ should return a 404 status code for invalid IDs

  POST /api/employees
POST /api/employees/ 201 99 - 27.226 ms
    ✓ should create a valid employee
POST /api/employees/ 201 99 - 2.197 ms
    ✓ should return a 201 status code after employee creation
POST /api/employees/ 201 99 - 2.136 ms
    ✓ should return the newly-created employee after employee creation
POST /api/employees/ 201 99 - 3.856 ms
    ✓ should set new employees as currently-employed by default
POST /api/employees/ 400 - - 0.336 ms
    ✓ should return a 400 status code for invalid employees

  PUT /api/employees/:id
PUT /api/employees/1 200 111 - 3.036 ms
    ✓ should update the employee with the given ID
PUT /api/employees/1 200 111 - 2.318 ms
    ✓ should return a 200 status code after employee update
PUT /api/employees/1 200 111 - 1.888 ms
    ✓ should return the updated employee after employee update
PUT /api/employees/1 400 - - 0.767 ms
    ✓ should return a 400 status code for invalid employee updates

  DELETE /api/employees/:id
DELETE /api/employees/1 200 96 - 2.367 ms
    ✓ should set the employee with the given ID as not currently-employed
DELETE /api/employees/1 200 96 - 2.810 ms
    ✓ should return a 200 status code after employee delete
DELETE /api/employees/1 200 96 - 2.647 ms
    ✓ should return the deleted employee after employee delete

  GET /api/employees/:employeeId/timesheets
GET /api/employees/1/timesheets 200 154 - 8.066 ms
    ✓ should return all timesheets of an existing employee
GET /api/employees/3/timesheets 200 17 - 0.760 ms
    ✓ should return an empty array for existing employees with no timesheets
GET /api/employees/2/timesheets 200 85 - 0.731 ms
    ✓ should return a status code of 200 for valid employees
GET /api/employees/999/timesheets 404 - - 0.351 ms
    ✓ should return a status code of 404 for invalid employees

  POST /api/employees/:employeeId/timesheets
POST /api/employees/2/timesheets 201 71 - 5.010 ms
    ✓ should create a valid timesheet
POST /api/employees/2/timesheets 201 71 - 4.396 ms
    ✓ should return a 201 status code after timesheet creation
POST /api/employees/2/timesheets 201 71 - 3.588 ms
    ✓ should return the newly-created timesheet after timesheet creation
POST /api/employees/2/timesheets 400 - - 1.115 ms
    ✓ should return a 400 status code for invalid timesheets
POST /api/employees/100/timesheets 404 - - 0.759 ms
    ✓ should return a 404 status code if an employee with the timesheet's employee ID doesn't exist

  PUT /api/employees/:employeeId/timesheets/:timesheetId
PUT /api/employees/1/timesheets/2 200 71 - 4.592 ms
    ✓ should update the timesheet with the given ID
PUT /api/employees/1/timesheets/2 200 71 - 3.131 ms
    ✓ should return a 200 status code after timesheet update
PUT /api/employees/1/timesheets/2 200 71 - 3.222 ms
    ✓ should return the updated timesheet after timesheet update
PUT /api/employees/1/timesheets/999 404 - - 1.164 ms
    ✓ should return a 404 status code for invalid timesheet IDs
PUT /api/employees/1/timesheets/2 400 - - 1.279 ms
    ✓ should return a 400 status code for invalid timesheet updates
PUT /api/employees/999/timesheets/1 404 - - 1.220 ms
    ✓ should return a 404 status code if an employee with the updated employee ID doesn't exist

  DELETE /api/employees/:employeeId/timesheets/:timesheetId
DELETE /api/employees/2/timesheets/1 204 - - 3.877 ms
    ✓ should remove the timesheet with the specified ID from the database
DELETE /api/employees/2/timesheets/1 204 - - 4.069 ms
    ✓ should return a 204 status code after timesheet delete
DELETE /api/employees/2/timesheets/999 404 - - 1.057 ms
    ✓ should return a 404 status code for invalid timesheet IDs

  GET /api/menus
GET /api/menus 200 91 - 1.419 ms
    ✓ should return all menus
GET /api/menus 200 91 - 0.483 ms
    ✓ should return a status code of 200

  GET /api/menus/:id
GET /api/menus/2 200 33 - 2.502 ms
    ✓ should return the menus with the given ID
GET /api/menus/2 200 33 - 0.588 ms
    ✓ should return a 200 status code for valid IDs
GET /api/menus/999 404 - - 0.358 ms
    ✓ should return a 404 status code for invalid IDs

  POST /api/menus
POST /api/menus/ 201 36 - 2.733 ms
    ✓ should create a valid menu
POST /api/menus/ 201 36 - 2.042 ms
    ✓ should return a 201 status code after menu creation
POST /api/menus/ 201 36 - 5.076 ms
    ✓ should return the newly-created menu after menu creation
POST /api/menus/ 400 - - 0.495 ms
    ✓ should return a 400 status code for invalid menus

  PUT /api/menus/:id
PUT /api/menus/2 200 40 - 3.939 ms
    ✓ should update the menu with the given ID
PUT /api/menus/2 200 40 - 3.979 ms
    ✓ should return a 200 status code after menu update
PUT /api/menus/2 200 40 - 6.654 ms
    ✓ should return the updated menu after menu update
PUT /api/menus/1 400 - - 0.764 ms
    ✓ should return a 400 status code for invalid menu updates

  DELETE /api/menus/:id
DELETE /api/menus/3 204 - - 3.982 ms
    ✓ should remove the menu with the specified ID from the database if that menu has no related menu items
DELETE /api/menus/3 204 - - 4.447 ms
    ✓ should return a 204 status code after menu delete
DELETE /api/menus/2 400 - - 0.796 ms
    ✓ should not delete menus with existing related menu items
DELETE /api/menus/2 400 - - 0.920 ms
    ✓ should return a 400 status code if deleted menu has existing related menu items

  GET /api/menus/:menuId/menu-items
GET /api/menus/1/menu-items 200 249 - 1.874 ms
    ✓ should return all menu items of an existing menu
GET /api/menus/3/menu-items 200 16 - 0.705 ms
    ✓ should return an empty array for existing menus with no menu items
GET /api/menus/2/menu-items 200 132 - 0.689 ms
    ✓ should return a status code of 200 for valid menus
GET /api/menus/999/menu-items 404 - - 1.340 ms
    ✓ should return a status code of 404 for invalid menus

  POST /api/menus/:menuId/menu-items
POST /api/menus/2/menu-items 201 115 - 4.373 ms
    ✓ should create a valid menuItem
POST /api/menus/2/menu-items 201 115 - 3.113 ms
    ✓ should return a 201 status code after menu item creation
POST /api/menus/2/menu-items 201 115 - 2.333 ms
    ✓ should return the newly-created menu item after menu item creation
POST /api/menus/2/menu-items 400 - - 0.795 ms
    ✓ should return a 400 status code for invalid menu items

  PUT /api/menus/:menuId/menu-items/:menuItemId
PUT /api/menus/1/menu-items/2 200 123 - 8.480 ms
    ✓ should update the menu item with the given ID
PUT /api/menus/1/menu-items/2 200 123 - 5.106 ms
    ✓ should return a 200 status code after menuItem update
PUT /api/menus/1/menu-items/2 200 123 - 2.907 ms
    ✓ should return the updated menu item after menu item update
PUT /api/menus/1/menu-items/999 404 - - 1.058 ms
    ✓ should return a 404 status code for invalid menu item IDs
PUT /api/menus/1/menu-items/2 400 - - 1.105 ms
    ✓ should return a 400 status code for invalid menu item updates

  DELETE /api/menus/:menuId/menu-items/:menuItemId
DELETE /api/menus/1/menu-items/2 204 - - 8.162 ms
    ✓ should remove the menu item with the specified ID from the database
DELETE /api/menus/1/menu-items/2 204 - - 4.071 ms
    ✓ should return a 204 status code after menu item delete
DELETE /api/menus/1/menu-items/999 404 - - 2.243 ms
    ✓ should return a 404 status code for invalid menu item IDs


  68 passing (1s)
  21 failing

  1) Employee Table should exist:
     Error: Employee table not found
      at Statement.prodDb.get (test/test.js:18:14)

  2) Employee Table should have name, position, wage, and is_current_employee columns with appropriate data types:
     Error: Error: SQLITE_ERROR: no such table: Employee
      at test/test.js:29:14
      at Statement.errBack (node_modules/sqlite3/lib/sqlite3.js:16:21)

  3) Employee Table should have a required name column:
     Error: Error: SQLITE_ERROR: no such table: Employee
      at test/test.js:48:14
      at Statement.errBack (node_modules/sqlite3/lib/sqlite3.js:16:21)

  4) Employee Table should have a required position column:
     Error: Error: SQLITE_ERROR: no such table: Employee
      at test/test.js:62:14
      at Statement.errBack (node_modules/sqlite3/lib/sqlite3.js:16:21)

  5) Employee Table should have a required wage column:
     Error: Error: SQLITE_ERROR: no such table: Employee
      at test/test.js:76:14
      at Statement.errBack (node_modules/sqlite3/lib/sqlite3.js:16:21)

  6) Employee Table is_current_employee should default to 1:
     Error: Error: SQLITE_ERROR: no such table: Employee
      at test/test.js:84:14
      at Statement.errBack (node_modules/sqlite3/lib/sqlite3.js:16:21)

  7) Timesheet Table should exist:
     Error: Timesheet table not found
      at Statement.prodDb.get (test/test.js:102:14)

  8) Timesheet Table should have id, name, and description columns with appropriate data types:
     Error: Error: SQLITE_ERROR: no such table: Timesheet
      at test/test.js:113:14
      at Statement.errBack (node_modules/sqlite3/lib/sqlite3.js:16:21)

  9) Timesheet Table should have a required hours column:
     Error: Error: SQLITE_ERROR: no such table: Timesheet
      at test/test.js:132:14
      at Statement.errBack (node_modules/sqlite3/lib/sqlite3.js:16:21)

  10) Timesheet Table should have a required rate column:
     Error: Error: SQLITE_ERROR: no such table: Timesheet
      at test/test.js:146:14
      at Statement.errBack (node_modules/sqlite3/lib/sqlite3.js:16:21)

  11) Timesheet Table should have a required date column:
     Error: Error: SQLITE_ERROR: no such table: Timesheet
      at test/test.js:160:14
      at Statement.errBack (node_modules/sqlite3/lib/sqlite3.js:16:21)

  12) Timesheet Table should have a required employee_id column:
     Error: Error: SQLITE_ERROR: no such table: Timesheet
      at test/test.js:174:14
      at Statement.errBack (node_modules/sqlite3/lib/sqlite3.js:16:21)

  13) Menu Table should exist:
     Error: Menu table not found
      at Statement.prodDb.get (test/test.js:184:14)

  14) Menu Table should have id and title columns with appropriate data types:
     Error: Error: SQLITE_ERROR: no such table: Menu
      at test/test.js:195:14
      at Statement.errBack (node_modules/sqlite3/lib/sqlite3.js:16:21)

  15) Menu Table should have a required title column:
     Error: Error: SQLITE_ERROR: no such table: Menu
      at test/test.js:214:14
      at Statement.errBack (node_modules/sqlite3/lib/sqlite3.js:16:21)

  16) MenuItem Table should exist:
     Error: MenuItem table not found
      at Statement.prodDb.get (test/test.js:224:14)

  17) MenuItem Table should have id, name, description, inventory, price, and menu_id columns with appropriate data types:
     Error: Error: SQLITE_ERROR: no such table: MenuItem
      at test/test.js:235:14
      at Statement.errBack (node_modules/sqlite3/lib/sqlite3.js:16:21)

  18) MenuItem Table should have a required name column:
     Error: Error: SQLITE_ERROR: no such table: MenuItem
      at test/test.js:254:14
      at Statement.errBack (node_modules/sqlite3/lib/sqlite3.js:16:21)

  19) MenuItem Table should have a required inventory column:
     Error: Error: SQLITE_ERROR: no such table: MenuItem
      at test/test.js:268:14
      at Statement.errBack (node_modules/sqlite3/lib/sqlite3.js:16:21)

  20) MenuItem Table should have a required price column:
     Error: Error: SQLITE_ERROR: no such table: MenuItem
      at test/test.js:282:14
      at Statement.errBack (node_modules/sqlite3/lib/sqlite3.js:16:21)

  21) MenuItem Table should have a required menu_id column:
     Error: Error: SQLITE_ERROR: no such table: MenuItem
      at test/test.js:296:14
      at Statement.errBack (node_modules/sqlite3/lib/sqlite3.js:16:21)
```

**Comment by luckyguy73** [comment]
if you run 'node migration.js' first then run 'mocha' all tests should pass.  where would i provide that instruction so someone would know to do that?

**Comment by Axkaban** [comment]
😅 I knew I forgot something... didn’t run migration. On that note, once you create your own projects and shared them on github it is also common practice to have regular information and necessary start commands, as well as anything people need to know about your app in a readMe file
